server:
  port: 8082
ping:
  host: http://localhost:8080
management:
  endpoints:
    web:
      exposure:
        include: prometheus
---
spring:
  profiles: docker
ping:
  host: http://ping-container:8080